apiVersion: v1
kind: Service
metadata:
 name: tomcat-app-svc
 namespace: Dev
 annotations:
   service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
 type: LoadBalancer
 selector:
   app: myapp
 ports:
   - port: 8080
     targetPort: 8080
