apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-in-file
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = your_access_key_id
    aws_secret_access_key = your_secret_key

# Mount AWS credentials as a volume.
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-1
spec:
  containers:
  - name: awscli-container
    image: kiran2361993/troubleshootingtools:v1
    volumeMounts:
    - name: secret-volume
      mountPath: /root/.aws/credentials
      subPath: credentials
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: aws-cred-in-file
