apiVersion: v1
kind: Pod
metadata:
  name: angular-web
  labels:
    app: webapp
spec:
  containers:
  - name: fleetman
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    ports:
    - containerPort: 80
