apiVersion: v1
kind: Service
metadata:
  name: my-service-for-angularweb
spec:
  type: LoadBalancer
  selector:
    app: webapp

  ports:
    - name: angularwebserver
      protocol: TCP
      port: 80
      targetPort: 80
