apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        node: worker_node-01 ## it will create pod in worker-node-01
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
