apiVersion: apps/v1
kind: Deployment
metadata:
  name: newnginx
spec:
  selector:
    matchLabels:
      app: newnginx
  template:
    metadata:
      labels:
        app: newnginx
    spec:
      containers:
      - name: newnginx
        image: nginx:latest
        ports:
        - containerPort: 9999
        volumeMounts:
        - mountPath: "/etc/nginx/conf.d/"
          name: nginxconfvol

      volumes:
      - name: nginxconfvol
        configMap:
          name: default-conf  
