apiVersion: v1
kind: Secret
metadata:
  name: aws-access-key
type: Opaque
data:
  AWS_ACCESS_KEY_ID: your-access-key-id encoded value paste here
  AWS_SECRET_ACCESS_KEY: your-secret-key-id encoded value paste here

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli
spec:
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      containers:
      - name: awscli
        image: kiran2361993/troubleshootingtools:v1
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-access-key
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
