apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: mohitdecoder/configsecrets:v1
        name: configsecrets
      imagePullSecrets:
      - name: dockerpwd #secrets are created via docker-registry

----

# this the way when you want to pass the secrets through docker-registry

# kubectl create secret docker-registry dockerpwd \
# --docker-server=docker.io --docker-username=mohitdecoder \
# --docker-password=yourdockerpassword\
# --docker-email=yourdockeremail

-----

