apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
    
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: object-counts
 namespace: development
spec:
 hard:
   requests.cpu: "1000m" #Minimum cpu usage
   limits.cpu: "2000m" #Maximum cpu limit
   requests.memory: 1Gi #Maximum memory usage
   limits.memory: 2Gi #Maximum memory usage for requests    
   pods: "10" #Maximum number of pods to create in namespace
   replicationcontrollers: "20" #Maximum number of replication controllers to create in namespace
   resourcequotas: "10" #Maximum number of resource quotas to create in namespace
   services: "5" #Maximum number of services to create in namespace

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-memory-min-max-demo-lr
  namespace: development
spec:
  limits:
  - max:
      cpu: "200m"
      memory: 128Mi
    min:
      cpu: "100m"
      memory: 100Mi
    type: Container