# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: mohitdecoder/tomcat11
        env:
        - name: DB_PORT ## NAME OF THE ENVIRONMENT VARIABLE INSIDE THE CONTAINER
          valueFrom:
            configMapKeyRef:
              name: test-cm ## name of the configmap yaml file
              key: db-port
        ports:
        - containerPort: 8080